-- Atelier seed: core rules + curated registry. Idempotent.
DELETE FROM rules WHERE source='core';
INSERT INTO rules (domain,key,value,source) VALUES
 ('code','file_word_budget','250 soft / 350 hard; exempt: md,json,yaml,lock,sql,generated','core'),
 ('code','dry','check graph/repo first; import, never rewrite; fix bugs in the shared function','core'),
 ('code','comments','sparse, intent-only; no narration; ponytail: notes for deliberate ceilings','core'),
 ('design','accent_budget','ONE brand accent, <=10% of any viewport','core'),
 ('design','theming','all colors as CSS variables in globals.css; semantic tokens in components; NEVER hardcode hex or per-page dark: overrides','core'),
 ('design','icons','Lucide 1.5px monochrome currentColor only; accent only on state','core'),
 ('design','motion','ease-out-expo entrances; springs 260/32/.9; stagger 60-80ms; reduced-motion fallback; transform/opacity only','core'),
 ('design','anti_style','no rainbow gradients, 3D emoji icons, colored icon circles, heavy shadows, bounce-ins, template grids','core'),
 ('structure','api_pattern','/api/v1/{feature}/{action}; thin endpoints, logic in services','core'),
 ('structure','monorepo','multiple frontends -> Turborepo apps/ + packages/','core'),
 ('auth','token_model','15min access JWT + 30day rotating single-use refresh; families; 60s grace; sliding window','core'),
 ('auth','refresh','silent one-shot timer + on-demand; single mutex per app; NEVER poll','core'),
 ('auth','redirect','login redirect is the LAST resort after silent refresh + session check','core'),
 ('stack','realtime','SSE or WebSockets, never polling; cache invalidation on write','core'),
 ('stack','llm_payloads','TOON over JSON for LLM-bound payloads; gRPC backend-to-backend','core'),
 ('stack','video_gen','ladder: GOOGLE_API_KEY (gemini-omni-flash-preview/Veo3.1) -> Vertex creds -> paste-prompt to Gemini app -> user mp4; never exit on missing token','core'),
 ('stack','credentials','project .env (gitignored), standard var names GOOGLE_API_KEY | GOOGLE_APPLICATION_CREDENTIALS+GOOGLE_CLOUD_PROJECT+GOOGLE_CLOUD_LOCATION; never in db or commits','core'),
 ('stack','assets','every raster -> webp via assets.py before serving; video -> frames -> webp for scrollytelling','core');

DELETE FROM registry WHERE kind IN ('component','skill','mcp');
INSERT INTO registry (kind,name,source,install,usage,meta) VALUES
 ('component','shadcn/ui','https://ui.shadcn.com','shadcn MCP / npx shadcn add','Radix primitives; restyle to tokens','a11y,ssr,dark'),
 ('component','Aceternity UI','https://ui.aceternity.com','aceternityui MCP','premium animated sections; strip to one accent','animated,dark'),
 ('component','ReactBits','https://reactbits.dev','react-bits MCP','micro-interaction components','animated'),
 ('component','Motion.dev','https://motion.dev','npm i motion','springs, layout morphs','animated'),
 ('component','MagicUI','https://magicui.design','npx magicui add','marketing components; token restyle required','animated,dark'),
 ('skill','ponytail','github:ponytail','/plugin install ponytail','minimalism enforcement on every coding task',''),
 ('skill','ui-ux-pro-max','local skill','installed','style/palette/font intelligence for UI work',''),
 ('mcp','code-review-graph','local','code-review-graph build','structural graph: impact radius, callers, tests-for',''),
 ('mcp','stitch','MCP','installed','high-fidelity screen generation + design systems',''),
 ('component','Cult UI','https://cult-ui.com','npx cult-ui add','shadcn-ecosystem components with tasteful motion (dialogs/tabs/buttons)','animated,shadcn'),
 ('component','Kokonut UI','https://kokonutui.com','npx kokonutui add','shadcn-ecosystem motion components for app UI','animated,shadcn'),
 ('component','Motion Primitives','https://motion-primitives.com','npm i motion','low-level composable Framer Motion blocks for custom effects','animated'),
 ('tool','magicui-cli','https://magicui.design','npx magicui-cli add <component>','fetch MagicUI components via CLI (no MCP needed)',''),
 ('tool','aceternity-cli','https://ui.aceternity.com','npx aceternity-ui@latest add <component>','fetch Aceternity components via CLI',''),
 ('tool','github-mcp','npm:@modelcontextprotocol/server-github','npx -y @modelcontextprotocol/server-github (needs PAT)','read any component library source from its repo — no hallucination',''),
 ('site','Iconoir','https://iconoir.com','npm i iconoir-react','1600+ free SVG icons; React/RN/CSS native','icons,free'),
 ('site','Phosphor Icons','https://phosphoricons.com','npm i @phosphor-icons/react','6 weights per icon; thin/light match design-law stroke discipline','icons,free'),
 ('site','Heroicons','https://heroicons.com','npm i @heroicons/react','Tailwind-native icon set','icons,free'),
 ('site','3dicons','https://3dicons.co','download png/gltf','1500+ free open-source 3D icons; color/angle editable in browser','3d,free'),
 ('site','Shapefest','https://shapefest.com','download png','free high-res 3D shapes/hands/letters (clay, glass, metal)','3d,free'),
 ('site','IconScout 3D','https://iconscout.com/3d-illustrations','download gltf','large 3D asset library, free tier, built-in glTF editor','3d,freemium');

DELETE FROM framework_map;
INSERT INTO framework_map (path,kind,purpose,load_when,links) VALUES
 ('skills/loop-engine/SKILL.md','skill','the operating loop, model routing table, clarification protocol, termination rule','any nontrivial task; deciding which model tier; when to stop or ask','architect,builder,summarizer'),
 ('skills/design-law/SKILL.md','skill','premium UI law: vocabulary, tokens, motion, icons, component canon, anti-slop, checklist','any UI/design/landing/component/animation work','gateway,asset-pipeline,registry'),
 ('skills/clean-code-law/SKILL.md','skill','250-word file budget, DRY via graph, comment policy, split strategies','writing or refactoring any source code','file_size_gate'),
 ('skills/structure-law/SKILL.md','skill','canonical file trees per stack + intake questions','scaffolding, moving files, new projects','nextjs,fastapi'),
 ('skills/auth-law/SKILL.md','skill','token rotation/families/grace, silent refresh, anti-patterns, shipping checklist','ANY authentication/session work','deploy-advisor'),
 ('skills/deploy-advisor/SKILL.md','skill','hosting matrix with real costs; decision rules','choosing hosting, estimating costs, CI/CD setup',''),
 ('skills/gateway/SKILL.md','skill','resolves authoritative design files (core + overlays)','START of any UI task, before design-law','design-law,learner'),
 ('skills/asset-pipeline/SKILL.md','skill','webp/frames tools, scrollytelling recipe, video-gen credential ladder + paste-prompt','images, video, media generation, storytelling sections','assets.py,ScrollScrub'),
 ('skills/stack-guides/nextjs.md','skill','Next.js decision rules + 5 agent mistakes','frontend work in Next.js','structure-law,design-law'),
 ('skills/stack-guides/fastapi.md','skill','FastAPI decision rules + 5 agent mistakes','Python backend/AI service work','structure-law'),
 ('agents/architect.md','agent','Opus planner: architecture + done-state contracts, never codes','/atelier:plan; architectural holes during build','loop-engine'),
 ('agents/builder.md','agent','Sonnet executor: implements plan tasks under all laws','/atelier:build task execution','loop-engine,clean-code-law'),
 ('agents/summarizer.md','agent','Haiku: digests, store updates, trivial edits','summaries, memory persistence, mechanical edits',''),
 ('agents/learner.md','agent','Sonnet ingester: references -> overlays + registry rows, never touches core','/atelier:learn ingestion','gateway'),
 ('agents/design-scout.md','agent','parallel scout: studies premium component source (Aceternity/ReactBits/MagicUI) and returns technique briefs + durable rules','spawn alongside any UI build/plan task','design-law,registry,builder'),
 ('db/store.py','tool','SQLite CLI: init/rules/registry/map/sql/exec, TOON-style pipe rows','reading rules, plans, criteria, registry, this map',''),
 ('mcp/assets/assets.py','tool','image->webp, video->webp frames','optimizing any raster; scrollytelling frames','asset-pipeline'),
 ('hooks/file_size_gate.py','tool','enforces 250/350-word file law on every write','automatic (PostToolUse hook)','clean-code-law'),
 ('hooks/session_start.py','tool','resumes active plan + unmet criteria on session start','automatic (SessionStart hook)','loop-engine'),
 ('templates/ScrollScrub.tsx','template','canvas scroll-scrubbed frame sequence component','building scrollytelling sections','asset-pipeline'),
 ('docs/REQUIREMENTS.md','doc','full product spec: what Atelier is and why','understanding scope; contributor onboarding',''),
 ('docs/IMPLEMENTATION-PLAN.md','doc','architecture, schema, phased build plan with gates','planning framework changes; contributor onboarding','');
